### ISSUE TITLE
Could not find publication, did you enter the correct name or id?

### ISSUE THREAD

**Issue by jerCarre** [philips-software/post-to-medium-action#16]
Hello,

I try tu use this github action but I have this error : 

```
Unhandled exception. System.Exception: Could not find publication, did you enter the correct name or id?
   at PostMediumGitHubAction.Services.MediumService.SubmitNewContentAsync() in /Action/Services/MediumService.cs:line 28
   at PostMediumGitHubAction.Program.Main(String[] args) in /Action/Program.cs:line 19
   at PostMediumGitHubAction.Program.<Main>(String[] args)
```

My workflow : 

```
name: publish-to-medium
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Read the post
        id: post
        run: echo "::set-output name=data::$(cat ./README.md)"
      - name: Create Medium Post
        uses: philips-software/post-to-medium-action@v0.3.4
        with:
          integration_token: "${{ secrets.MEDIUM_ACCESS_TOKEN }}"
          file: "./README.md"
          content_format: "markdown"
          publication_id: "PublicationName"
          publication_name: "publication"
          tags: "markdown,vega,vegalite,docsify,github"
          title: "Comment afficher le cours d'une crypto sur sa page github ?"
```

There's non article in medium.

Could you help me ?

**Comment by Brend-Smits** [comment]
Hey @jerCarre,
Sorry for the delayed response. I missed this due to the holidays! 
The publication Name or Id has now been made optional so you can remove those. If you do not want to publish your article under a publication, you can leave them both out and it will automatically post it under the account of which you are authenticating. 

Your new workflow would be as follows:

```YAML
name: publish-to-medium
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Read the post
        id: post
        run: echo "::set-output name=data::$(cat ./README.md)"
      - name: Create Medium Post
        uses: philips-software/post-to-medium-action@v0.4.0
        with:
          integration_token: "${{ secrets.MEDIUM_ACCESS_TOKEN }}"
          file: "./README.md"
          content_format: "markdown"
          tags: "markdown,vega,vegalite,docsify,github"
          title: "Comment afficher le cours d'une crypto sur sa page github ?"
```

I released a new version https://github.com/philips-software/post-to-medium-action/releases/tag/v0.4.0 to make this possible.

Thank you for opening a new issue, please let me know if you require additional help.
