### ISSUE TITLE
Define frontmatter in expression syntax

### ISSUE THREAD

**Issue by Brend-Smits** [philips-software/post-to-medium-action#9]
Frontmatter should not be by convention, but should be allowed to be custom defined. This allows maximum flexibility.
Take the following scenario:
- User wants to cross-post to Medium using our action, but also wants to post to their own blog which uses Gatsby(Gatsby has their own Frontmatter).
  
It would be great if the user could define their own frontmatter to not have to define multiple different ones for each action.
Example:
```yaml
        name: Create Medium Post
        uses: philips-software/post-to-medium-action@v0.2
        with:
           integration_token: "${{ secrets.INTEGRATION_TOKEN }}"
           file: ${{ steps.changed-files.outputs.added_files }}
           content_format: "markdown"
           notify_followers: "false"
           publication_name: "#!#fm.publication_name"
           tags: "#!#fm.categories"
           title: "#!#fm.title"
```

`#!#` syntax is placeholder, and is subject to change. 
https://github.com/philips-labs/tabia#filter uses such an approach using a Golang library to define filters. Implementation link: https://github.com/philips-labs/tabia/blob/c6b5005250d791ec2a64ae7f824692ffc6f208f6/lib/github/filter.go

To do:

- [ ] Search for equivalent expression NuGet package.
